import { DownloadItem } from './types';

// Curated high quality artwork collection for restored tracks
const ALBUM_COVERS = [
  'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=300&q=80',
  'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=300&q=80',
  'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&q=80',
  'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=300&q=80',
  'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=300&q=80',
  'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=300&q=80',
  'https://images.unsplash.com/photo-1445985543470-41fba5c3144a?w=300&q=80',
  'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=300&q=80',
  'https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=300&q=80',
  'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=300&q=80',
];

export const INITIAL_RESTORE_TRACKS: DownloadItem[] = [
  // 2 Single Tracks
  {
    id: 'hist_single_1',
    url: '',
    title: 'Osmanlı Nakşibendi zikir Tam Versiyon (Slowed)',
    uploader: 'Payitaht 1299',
    thumbnail: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?w=300&q=80',
    duration: 188,
    formatType: 'mp3',
    quality: '320',
    status: 'completed',
    percent: 100,
    outputFile: 'C:\\Users\\musta\\Downloads\\Osmanlı Nakşibendi zikir Tam Versiyon (Slowed).mp3',
    createdAt: Date.now() - 3600000,
    completedAt: Date.now() - 3600000,
  },
  {
    id: 'hist_single_2',
    url: '',
    title: 'Pikapta Raks - Ben Öldüm Sen Solasın',
    uploader: 'Pikapta Raks',
    thumbnail: 'https://images.unsplash.com/photo-1539375665275-f9de415ef9ac?w=300&q=80',
    duration: 195,
    formatType: 'mp3',
    quality: '320',
    status: 'completed',
    percent: 100,
    outputFile: 'C:\\Users\\musta\\Downloads\\Pikapta Raks - Ben Öldüm Sen Solasın.mp3',
    createdAt: Date.now() - 3700000,
    completedAt: Date.now() - 3700000,
  },

  // 38 Tracks of "Türküler En İyi 50" Playlist
  ...[
    '01 - Neset Ertas   Ah Yalan Dünya',
    '02 - Cengiz ÖZKAN - Bir Ay Doğar',
    '03 - Abdal - Ervah-ı Ezelde',
    '04 - İncesaz feat. Cengiz Özkan - Elif Dedim Be Dedim I Elif © 2007 Kalan Müzik',
    '05 - Kivircik Ali - Isirgan Otu',
    '06 - Kazım Koyuncu - Gelevera Deresi',
    '07 - Selda Bagcan - Gesi Bağları',
    '08 - Musa Eroğlu - Telli Turnam',
    '09 - Cem Adrian - Sen Gel Diyorsun (Öf Öf)',
    '10 - Kum Gibi (Ahmet Kaya)',
    '11 - Deniz Üstünde Fener (Selçuk Balcı)',
    '12 - selda bağcan öyle bir yerdeyim ki',
    '13 - Aşık Veysel - Uzun İnce Bir Yoldayım (Uzun Versiyon)',
    '14 - Çukur - Ayrılık Hasreti - Seyfi Yerlikaya & Özge Öz Erdoğan (Orijinal Dizi Müziği)',
    '15 - Erisin Dağların Karı (Tolga Sağ, Erdal Erzincan, Yılmaz Çelik) Official Audio',
    '16 - Mimoza Çiçeğim - Volkan Konak',
    '17 - Yavuz Bingöl - Kara Tren',
    '18 - Tolga Çandar - Ah Bir Ataş Ver Cigaramı Yakayım',
    '19 - Şevval Sam - Ander Sevdaluk I Karadeniz © 2008 Kalan Müzik',
    '20 - Mahzuni Şerif - Bilmem Ağlasam mı Ağlamasam mı ｜ Mevlam İki Göz Vermiş',
    '21 - ERDAL ERZİNCAN - NEM KALDI',
    '22 - İsmail Altunsaray  - Kız Senin I Official Music Video © 2011 Kalan Müzik',
    '23 - Dalgalan Karadeniz (Resul Dindar) Official Audio #dalgalankaradeniz #resuldindar #karadenizşarkıları',
    '24 - Hastane Önünde İncir Ağacı (Hüseyin Turan) Official Audio #hastaneönündeincirağacı #hüseyinturan',
    '25 - Musa Eroğlu - Halil İbrahim',
    '26 - Cem Adrian - Ela Gözlüm (Official Audio)',
    '27 - Deniz Toprak - Diz Dize ｜ Sarıl Bana ｜ © Arda Müzik 2013',
    '28 - Şevval Sam - Hey Gidi Karadeniz - Ander Sevdaluk',
    '30 - Cengiz Özkan- Ben Denizde Bir Gemi',
    '31 - Onur Akın Seviyorum Seni   YouTube',
    '32 - Kıvırcık Ali & Yıldız Tilbe - Al Ömrümü ( DÜET )',
    '33 - Mümin Sarıkaya - Ben Yoruldum Hayat (Official Video)',
    '34 - Volkan Konak - Herkesin Bir Derdi Var',
    '35 - Grup Abdal - Altın Yüzüğüm Kırıldı [ Ozanca © 2013 Kalan Müzik ]',
    '36 - Sabahat Akkiraz - Değme Felek',
    '37 - Sukriye Tutkun - Gücüm Yetene Kadar',
    '38 - Güler Duman - Sazım',
    '39 - Yavuz Bingöl - Saçlarını Taramışsın',
  ].map((rawTitle, idx) => {
    const cleanTitle = rawTitle.replace(/^\d+\s*-\s*/, '');
    const parts = cleanTitle.split(' - ');
    const uploader = parts.length > 1 ? parts[0] : 'Türküler En İyi 50';
    return {
      id: `hist_turkuler_${idx + 1}`,
      url: '',
      title: cleanTitle,
      uploader: uploader,
      thumbnail: ALBUM_COVERS[idx % ALBUM_COVERS.length],
      duration: 240,
      formatType: 'mp3' as const,
      quality: '320',
      status: 'completed' as const,
      percent: 100,
      outputFile: `C:\\Users\\musta\\Downloads\\Türküler En İyi 50\\${rawTitle}.mp3`,
      createdAt: Date.now() - 4000000 + idx * 1000,
      completedAt: Date.now() - 4000000 + idx * 1000,
      subfolderName: 'Türküler En İyi 50',
    };
  }),
];
